/** Mã lỗi — docs/11-api-design.md mục 3. Ổn định, là hợp đồng với client. */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  STALE_VERSION: 'STALE_VERSION',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  QUOTATION_EXPIRED: 'QUOTATION_EXPIRED',
  QUOTATION_ALREADY_RESPONDED: 'QUOTATION_ALREADY_RESPONDED',
  INVOICE_IMMUTABLE: 'INVOICE_IMMUTABLE',
  CREDIT_LIMIT_EXCEEDED: 'CREDIT_LIMIT_EXCEEDED',
  TECHNICIAN_NOT_CERTIFIED: 'TECHNICIAN_NOT_CERTIFIED',
  POWERTRAIN_MISMATCH: 'POWERTRAIN_MISMATCH',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Landing / Sales — SRS Phase 1 mục 12
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  CONTENT_NOT_PUBLISHED: 'CONTENT_NOT_PUBLISHED',
  CONTENT_GONE: 'CONTENT_GONE',
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  PRODUCT_NOT_PUBLISHABLE: 'PRODUCT_NOT_PUBLISHABLE',
  SEO_VALIDATION_FAILED: 'SEO_VALIDATION_FAILED',
  EXPERIENCE_NOT_PUBLISHABLE: 'EXPERIENCE_NOT_PUBLISHABLE',
  EXPERIENCE_NOT_FOUND: 'EXPERIENCE_NOT_FOUND',
  PUBLISHED_CONTEXT_STALE: 'PUBLISHED_CONTEXT_STALE',
  INVALID_LEAD_TRANSITION: 'INVALID_LEAD_TRANSITION',
  LEAD_ALREADY_CLOSED: 'LEAD_ALREADY_CLOSED',
  ASSIGNEE_OUT_OF_SCOPE: 'ASSIGNEE_OUT_OF_SCOPE',

  /**
   * 🔒 Có quyền, nhưng KHÔNG cho đối tượng đó.
   *
   * Tách khỏi 403 có chủ ý: 403 nghĩa là "vai của bạn không làm được việc này",
   * còn đây nghĩa là "vai của bạn làm được, nhưng không phải với chi nhánh này".
   * Gộp hai chuyện lại thì một bài soát "ai bị từ chối vì thiếu quyền" bị trộn
   * lẫn với những lần từ chối vì sai phạm vi — và bài soát đó là cách duy nhất
   * phát hiện ma trận quyền khai sai.
   */
  BRANCH_OUT_OF_SCOPE: 'BRANCH_OUT_OF_SCOPE',
  THEME_NOT_APPLICABLE: 'THEME_NOT_APPLICABLE',
  LANDING_PAGE_NOT_PUBLISHABLE: 'LANDING_PAGE_NOT_PUBLISHABLE',
  PREVIEW_NOT_FOUND: 'PREVIEW_NOT_FOUND',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const HTTP_STATUS_OF_ERROR: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INVALID_STATE_TRANSITION: 409,
  STALE_VERSION: 409,
  RESOURCE_CONFLICT: 409,
  INSUFFICIENT_STOCK: 409,
  QUOTATION_EXPIRED: 409,
  QUOTATION_ALREADY_RESPONDED: 409,
  INVOICE_IMMUTABLE: 409,
  CREDIT_LIMIT_EXCEEDED: 409,
  TECHNICIAN_NOT_CERTIFIED: 422,
  POWERTRAIN_MISMATCH: 422,
  APPROVAL_REQUIRED: 422,
  IDEMPOTENCY_KEY_REUSED: 422,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  SITE_NOT_FOUND: 404,
  CONTENT_NOT_PUBLISHED: 404,
  CONTENT_GONE: 410,
  SLUG_ALREADY_EXISTS: 409,
  PRODUCT_NOT_PUBLISHABLE: 422,
  SEO_VALIDATION_FAILED: 422,
  EXPERIENCE_NOT_PUBLISHABLE: 422,
  EXPERIENCE_NOT_FOUND: 404,
  PUBLISHED_CONTEXT_STALE: 409,
  INVALID_LEAD_TRANSITION: 409,
  LEAD_ALREADY_CLOSED: 409,
  ASSIGNEE_OUT_OF_SCOPE: 422,
  BRANCH_OUT_OF_SCOPE: 422,
  /*
   * Bảng màu ĐÚNG DẠNG nhưng không dùng được: cặp màu trượt AA, nền quá sáng,
   * bo góc ngoài thang. 422 chứ không phải 400 — cùng lý do với
   * `SEO_VALIDATION_FAILED`: payload đọc được và hợp lệ về kiểu, thứ nó không
   * qua được là một CỔNG NỘI DUNG.
   */
  THEME_NOT_APPLICABLE: 422,
  LANDING_PAGE_NOT_PUBLISHABLE: 422,
  PREVIEW_NOT_FOUND: 404,
};
