'use client';

import { use, useEffect, useMemo, useState } from 'react';
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { LandingPageDocument, LandingSection, type LandingSectionType } from '@garageos/contracts';
import { errorMessage } from '@/lib/client';
import { useCloneLandingDraft, useLandingPage, useLandingPublication, useSaveLandingDraft } from '@/features/landing-builder/queries';
import styles from './builder.module.css';

const labels: Record<LandingSectionType, string> = { hero: 'Hero', vehicleShowcase: 'Featured vehicles', journey: 'Ownership journey', imageText: 'Image + text', trust: 'Trust', richText: 'Rich text', cta: 'Final CTA' };

export default function LandingBuilderPage({ params }: { params: Promise<{ pageId: string }> }): React.ReactElement {
  const { pageId } = use(params); const page = useLandingPage(pageId); const save = useSaveLandingDraft(pageId); const clone = useCloneLandingDraft(pageId); const publication = useLandingPublication(pageId);
  const source = page.data?.draft ?? page.data?.published ?? null;
  const [document, setDocument] = useState<LandingPageDocument | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [viewport, setViewport] = useState<'desktop'|'tablet'|'mobile'>('desktop'); const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  useEffect(() => { if (source !== null) { setDocument(source.document); setSelectedId(source.document.sections[0]?.id ?? null); } }, [source]);
  const selected = useMemo(() => document?.sections.find((section) => section.id === selectedId) ?? null, [document, selectedId]);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  function change(next: LandingPageDocument) { setDocument(LandingPageDocument.parse(next)); }
  function onDragEnd(event: DragEndEvent) { if (document === null || event.over === null || event.active.id === event.over.id) return; const from = document.sections.findIndex((item) => item.id === event.active.id); const to = document.sections.findIndex((item) => item.id === event.over?.id); change({ ...document, sections: arrayMove(document.sections, from, to) }); }
  function add(type: LandingSectionType) { if (document === null) return; const id = crypto.randomUUID(); const section = template(type, id); change({ ...document, sections: [...document.sections, section] }); setSelectedId(id); }
  async function openPreview() { const result = await publication.createPreview.mutateAsync(); const origin = process.env.NEXT_PUBLIC_LANDING_PREVIEW_ORIGIN ?? 'http://localhost:3003'; setPreviewUrl(`${origin}/preview/${encodeURIComponent(result.token)}`); }
  if (page.isLoading || document === null) return <main className="container"><p className="note">Đang mở builder…</p></main>;
  const draftVersion = page.data?.draft?.version ?? 0;
  return <main className={styles.builder}>
    <header className={styles.toolbar}><div><a href="/website">← Website</a><strong>Homepage</strong><span>{save.isPending ? 'Đang lưu…' : page.data?.draft === null ? 'Published' : 'Draft'}</span></div><div className={styles.actions}><div role="group" aria-label="Khung xem trước">{(['desktop','tablet','mobile'] as const).map((size) => <button className={viewport === size ? styles.active : ''} key={size} onClick={() => setViewport(size)}>{size}</button>)}</div><button className="btn btn-secondary" disabled={publication.createPreview.isPending} onClick={() => void openPreview()}>Preview</button>{page.data?.draft === null ? <button className="btn" disabled={clone.isPending} onClick={() => clone.mutate()}>Tạo draft để sửa</button> : <><button className="btn" disabled={save.isPending} onClick={() => save.mutate({ version: draftVersion, document })}>Lưu draft</button><button className="btn" disabled={publication.publish.isPending} onClick={() => publication.publish.mutate(page.data!.version)}>Publish</button></>}</div></header>
    {(save.error || publication.publish.error || publication.createPreview.error || publication.rollback.error) && <p className="error" role="alert">{errorMessage(save.error ?? publication.publish.error ?? publication.createPreview.error ?? publication.rollback.error)}</p>}
    <div className={styles.panels}>
      <aside className={styles.structure}><h2>Sections</h2><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}><SortableContext items={document.sections.map((section) => section.id)} strategy={verticalListSortingStrategy}>{document.sections.map((section) => <SectionRow key={section.id} section={section} selected={section.id === selectedId} onSelect={() => setSelectedId(section.id)} onToggle={() => change({ ...document, sections: document.sections.map((item) => item.id === section.id ? { ...item, enabled: !item.enabled } : item) })} onDuplicate={() => { const duplicate = { ...section, id: crypto.randomUUID() } as LandingSection; change({ ...document, sections: [...document.sections, duplicate] }); }} onDelete={() => { if (document.sections.length > 1 && confirm(`Xóa ${labels[section.type]}?`)) { const sections = document.sections.filter((item) => item.id !== section.id); change({ ...document, sections }); setSelectedId(sections[0]?.id ?? null); } }} />)}</SortableContext></DndContext><details className={styles.add}><summary>+ Add section</summary>{(Object.keys(labels) as LandingSectionType[]).map((type) => <button key={type} onClick={() => add(type)}>{labels[type]}</button>)}</details></aside>
      <section className={styles.preview} aria-label="Landing preview"><div className={`${styles.frame} ${styles[viewport]}`}>{previewUrl === null ? <DocumentSnapshot document={document} /> : <iframe title="Landing preview" src={previewUrl} />}</div><p className="note">Preview uses the landing renderer; save the draft before publishing.</p></section>
      <aside className={styles.inspector}><h2>Inspector</h2>{selected === null ? <p className="note">Chọn một section để chỉnh sửa.</p> : <Inspector section={selected} onChange={(next) => change({ ...document, sections: document.sections.map((item) => item.id === next.id ? next : item) })} />}{page.data?.published !== null && <button className="btn btn-secondary" disabled={publication.rollback.isPending} onClick={() => publication.rollback.mutate()}>Rollback bản trước</button>}</aside>
    </div>
  </main>;
}

function SectionRow({ section, selected, onSelect, onToggle, onDuplicate, onDelete }: { section: LandingSection; selected: boolean; onSelect: () => void; onToggle: () => void; onDuplicate: () => void; onDelete: () => void }) { const sortable = useSortable({ id: section.id }); return <div ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} className={`${styles.sectionRow} ${selected ? styles.selected : ''}`}><button {...sortable.attributes} {...sortable.listeners} aria-label={`Kéo ${labels[section.type]}`} className={styles.handle}>⠿</button><button className={styles.sectionName} onClick={onSelect}>{labels[section.type]}</button><button onClick={onToggle} aria-label={section.enabled ? 'Ẩn section' : 'Hiện section'}>{section.enabled ? '●' : '○'}</button><details><summary aria-label="Thao tác section">•••</summary><button onClick={onDuplicate}>Duplicate</button><button onClick={onDelete}>Delete</button></details></div>; }
function Inspector({ section, onChange }: { section: LandingSection; onChange: (section: LandingSection) => void }) { const updateText = (field: 'title'|'body'|'description'|'eyebrow', value: string) => onChange(LandingSection.parse({ ...section, content: { ...section.content, [field]: value } })); return <form className={styles.form} onSubmit={(event) => event.preventDefault()}><label>Section type<input value={labels[section.type]} disabled /></label>{'title' in section.content && <label>Title<input value={section.content.title ?? ''} onChange={(event) => updateText('title', event.target.value)} /></label>}{'eyebrow' in section.content && <label>Eyebrow<input value={section.content.eyebrow ?? ''} onChange={(event) => updateText('eyebrow', event.target.value)} /></label>}{'body' in section.content && <label>Body<textarea rows={5} value={section.content.body ?? ''} onChange={(event) => updateText('body', event.target.value)} /></label>}{'description' in section.content && <label>Description<textarea rows={4} value={section.content.description ?? ''} onChange={(event) => updateText('description', event.target.value)} /></label>}<label>Theme<select value={section.appearance.theme} onChange={(event) => onChange(LandingSection.parse({ ...section, appearance: { ...section.appearance, theme: event.target.value } }))}><option value="light">Light</option><option value="dark">Dark</option><option value="brand">Brand</option></select></label><label>Spacing<select value={section.appearance.spacing} onChange={(event) => onChange(LandingSection.parse({ ...section, appearance: { ...section.appearance, spacing: event.target.value } }))}><option value="compact">Compact</option><option value="normal">Normal</option><option value="spacious">Spacious</option></select></label></form>; }
function DocumentSnapshot({ document }: { document: LandingPageDocument }) { return <div className={styles.snapshot}>{document.sections.filter((section) => section.enabled).map((section) => { const theme = section.appearance.theme; return <section key={section.id} className={styles[`theme${theme.charAt(0).toUpperCase()}${theme.slice(1)}`]}><p>{labels[section.type]}</p>{'title' in section.content && <h2>{section.content.title}</h2>}{'description' in section.content && <p>{section.content.description}</p>}{'body' in section.content && <p>{section.content.body}</p>}</section>; })}</div>; }
function template(type: LandingSectionType, id: string): LandingSection { const base = { id, schemaVersion: 1 as const, enabled: true, appearance: { theme: 'light', alignment: 'left', spacing: 'normal', width: 'contained' } }; switch (type) { case 'hero': return LandingSection.parse({ ...base, type, content: { title: 'Một hành trình sở hữu, liên tục.' } }); case 'vehicleShowcase': return LandingSection.parse({ ...base, type, content: { title: 'Những mẫu xe được chọn', productIds: [] } }); case 'journey': return LandingSection.parse({ ...base, type, content: { title: 'Từ tìm hiểu đến lịch sử chăm sóc' } }); case 'imageText': return LandingSection.parse({ ...base, type, content: { title: 'Dịch vụ đồng hành', body: 'Nội dung dịch vụ.' } }); case 'trust': return LandingSection.parse({ ...base, type, content: { title: 'Minh bạch từ ngày đầu' } }); case 'richText': return LandingSection.parse({ ...base, type, content: { body: 'Nội dung biên tập.' } }); case 'cta': return LandingSection.parse({ ...base, type, content: { title: 'Bắt đầu hành trình của bạn', cta: { label: 'Đăng ký lái thử', href: '/lien-he' } } }); } }
